apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: travel-planner-dev
namePrefix: dev-

replicas:
  - name: travel-planner
    count: 1

patches:
  - target:
      kind: Deployment
      name: travel-planner
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
