spring:
  application:
    name: travel-planner

  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/travel_planner
    username: travel_user
    password: travel_password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        temp:
          use_jdbc_metadata_defaults: false

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  access-token-expiration: 900000
  refresh-token-expiration: 604800000

management:
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.zaxxer.hikari: DEBUG
    org.springframework.jdbc: DEBUG
    org.springframework.boot.actuate.jdbc: DEBUG